// <auto-generated />
namespace Document_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update_document_table_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_document_table_));
        
        string IMigrationMetadata.Id
        {
            get { return "202005111643268_update_document_table_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
